name: Staleness

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Friendly Reminder for this issue'
        stale-pr-message: 'Friendly Reminder for this pull request'
        stale-issue-label: 'no issue activity'
        stale-pr-label: 'no issue activity'
